# Generated by Django 3.1.7 on 2021-03-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
