# Generated by Django 3.1.7 on 2021-03-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0002_message_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='send_attempt_over',
            field=models.BooleanField(default=False),
        ),
    ]
